### PR TITLE
Add ability to set the default font.

### PR DESCRIPTION
**Pull request by dawnmist**
Partial fix for #54 - allows the user to specify the fontFamily to use as the default font.

### CODE REVIEW

**Comment by jacobp100** [comment]
So React Native has behaviour where setting `fontFamily: 'System'` uses the system font (with this being the default font family). Should we copy this behaviour?

It would probably fix a few bugs like,

```js
<Text style={{ fontFamily: 'Comic Sans' }}>
  Some text <Text style={{ fontFamily: 'System' }}>etc</Text>
</Text>
```

Which is something I've had to do before!

**Comment by orta** [comment]
Yeah, I agree with @jacobp100 - thanks for doing this @dawnmist !

**Comment by orta** [comment]
I've also given you the rights to merge @dawnmist - I'll try get some time on #50 which I'm hoping can fix CI, and make this  project viable for me again

**Comment by orta** [comment]
Nice one!

**Comment by orta** [comment]
I'll ship a release

**Pull request merged**
