### PR TITLE
Fix text position

### LINKED ISSUE #44: Layout regression on master
Hey there, it looks like there's a regression in laying out content on master:

**v0.0.24:**
image

**master:**
screen shot 2018-01-24 at 10 32 56 am

It seems likely this has to do with the text layout stuff that landed on master.

### PR DESCRIPTION
**Pull request by jacobp100**
Fixes #44

### CODE REVIEW

**Comment by jacobp100** [comment]
Sorry, I branched from the `borders` branch, and I don't know how to make it as if I branched from master. If this is a problem, I can just copy the work over to another branch!

**Comment by orta** [comment]
It's not a problem, I was hoping to get that merged ASAP

**Comment by orta** [comment]
I'd like to get this in, are you happy with it?

**Comment by jacobp100** [comment]
Yep!

**Comment by orta** [comment]
Fails look unrelated

**Comment by orta** [comment]
Cool, let's get this in then

**Pull request merged**
