### PR TITLE
Text layout

### PR DESCRIPTION
**Pull request by jacobp100**
Implements text breaking for `<Text>` elements and outputs to `<tspan>` elements.

Requires the font file for layout. How do we handle this? Should we bundle some fonts so it 'just works'? Should we try and find fonts on the users system? Should we expose a hook to load a font?

We need to look at the best way to handle text content on nodes. Before, there was the `textContent` parameter, but this not the most ideal solution any more. We also have to constantly check for text nodes so we don't recurse into their children.

### CODE REVIEW

**Comment by orta** [comment]
The font's one is interesting because you don't want it to differ between CI and your host app, think we might need a way to be able to declare the fonts locally somehow?

**Comment by jacobp100** [comment]
That’s sort of what’s currently done, although it’s hard coded to the path of a system font. Maybe we could just do manual font configuration for now, and look at trying to find system fonts later.

**Comment by orta** [comment]
That seems reasonable to me 👍

**Comment by jacobp100** [comment]
I got loading system fonts working. I've added a `README` section that should explain how it works.

I can't figure out how to get `import` statements to work with the modules I `require`d. Is there a trick in TypeScript for this?

**Comment by orta** [comment]
> Should we just bundle some font files for the tests?

Yeah probably, most things on https://fontlibrary.org/ are OSS, [this is apache](https://fontlibrary.org/en/font/fog-sans)

**Comment by jacobp100** [comment]
I like that font! I just thought of a few ideas for comparability for the generated SVG.

* Use a font like Arimo that’s a metric equivalent to Arial/Helvetica and add font fallbacks
* Experiment with `@font-face` in SVGs
* Convert fonts to curves (possibly as a post-processing step)

The first one doesn’t help compatibility when the user adds custom fonts. And to an extent, neither does the second.

Would be interested to hear your thoughts!

**Comment by orta** [comment]
Is this that we have to have the font metrics in code before hand?

**Comment by jacobp100** [comment]
We use the font metrics for text breaking. But if you render the SVG with a different font, the rendered text could exceed the original bounds

**Comment by orta** [comment]
[last time](https://github.com/jest-community/jest-snapshots-svg/pull/30) we looked at this we ended up with using a few defaults and then just falling back to times new roman - which seem fine with me.

**Comment by jacobp100** [comment]
I just added an API to specify fallbacks. It's not ideal, and we will probably want to revisit that later. But for now, it works!

**Comment by orta** [comment]
👍

**Comment by orta** [comment]
awesome

**Pull request merged**
